aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: false
  hash_algorithm: sha512
  key: $6$Q5Pg0k.kTwgJ89NX$j0438CJoJx2RiuCsygN8GtpTrWPNWlZQIytcMQQRhLhv7oK0HNaXgbhDKsUUksrL22UDMx9tMfE9ufd0YJmkx1
ethernet_interfaces:
- name: Ethernet11
  description: MLAG_campus-a-leaf2a_Ethernet11
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: campus-a-leaf2a
  peer_interface: Ethernet11
  peer_type: mlag_peer
- name: Ethernet12
  description: MLAG_campus-a-leaf2a_Ethernet12
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: campus-a-leaf2a
  peer_interface: Ethernet12
  peer_type: mlag_peer
- name: Ethernet3
  shutdown: false
  ip_address: 169.254.10.2/31
  peer_type: l3_interface
  switchport:
    enabled: false
- name: Management1
  lldp:
    transmit: false
    receive: false
hostname: campus-a-leaf2b
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$RWWNi/U4IjK9U3Nv$/bMitcVhMFiqvUIJtAAeTOTSyvqAHK.XpJi12NI0.YTJlzbl9FiCGi2EDfIWo14Evi/sj5i1Rxspmkbso0Tun1
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$6PorspAoWf2hUSNp$3CT1iPrvr7uhgCdAN2QBZuO7Aqu..EFjOK5SHUXSP44qJ91OQ/I.88B4iyDufM35wwqS1JhbmS3ejsDAxvOGL/
- name: robert
  privilege: 15
  role: network-admin
  no_password: true
  ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK7U+usFHr9Xhqph3HcmaWpi/Tjl0a3aof1AQRvSXuOw redmonds@redmonds
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 172.16.10.16/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 172.16.11.15/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: default
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: default
  ip_address: 192.168.0.36/24
  type: oob
  gateway: 192.168.0.1
metadata:
  is_deployed: true
  platform: vEOS-LAB
  dc_name: CAMPUS_A
  fabric_name: HCA
mlag_configuration:
  domain_id: campus-a-leaf2
  local_interface: Vlan4094
  peer_address: 10.255.255.28
  peer_address_heartbeat:
    peer_ip: 192.168.0.35
    vrf: default
  dual_primary_detection_delay: 5
  peer_link: Port-Channel11
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel11
  description: MLAG_campus-a-leaf2a_Port-Channel11
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 2-4094
      groups:
      - MLAG
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 172.16.10.0/24 eq 32
  - sequence: 20
    action: permit 172.16.11.0/24 eq 32
- name: PL-SVI-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    action: permit 10.10.10.0/24
  - sequence: 20
    action: permit 10.10.20.0/24
  - sequence: 30
    action: permit 10.10.30.0/24
  - sequence: 40
    action: permit 10.10.40.0/24
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
    set:
    - origin incomplete
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  - sequence: 30
    type: permit
    match:
    - ip address prefix-list PL-SVI-VRF-DEFAULT
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-SVI-VRF-DEFAULT
- name: RM-BGP-UNDERLAY-PEERS-OUT
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - ip address prefix-list PL-SVI-VRF-DEFAULT
  - sequence: 20
    type: permit
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
router_bgp:
  as: '65102'
  router_id: 172.16.10.16
  distance:
    external_routes: 20
    internal_routes: 200
    local_routes: 200
  graceful_restart:
    enabled: true
  maximum_paths:
    paths: 4
    ecmp: 4
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65102'
    description: campus-a-leaf2a
    next_hop_self: true
    password: vnEaG8gMeQf3d3cN6PktXQ==
    send_community: all
    maximum_routes: 12000
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    password: AQQvKeimxJu+uGQ/yYvv9w==
    send_community: all
    maximum_routes: 12000
    route_map_out: RM-BGP-UNDERLAY-PEERS-OUT
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    password: q+VNViP5i4rVjW1cxFv2wA==
    send_community: all
    maximum_routes: 0
  - name: WAN
    remote_as: '65534'
    description: WAN Routers
    bfd: true
    send_community: all
    maximum_routes: 12000
  neighbors:
  - ip_address: 10.255.254.28
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    peer: campus-a-leaf2a
    description: campus-a-leaf2a_Vlan4093
  - ip_address: 169.254.10.3
    peer_group: WAN
    description: WAN Router
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlan_aware_bundles:
  - name: default
    rd: 172.16.10.16:10
    route_targets:
      both:
      - '10:10'
    redistribute_routes:
    - learned
    vlan: 10,20,30,40
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
    - name: WAN
      activate: true
  vrfs:
  - name: default
    rd: 172.16.10.16:10
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '10:10'
      export:
      - address_family: evpn
        route_targets:
        - '10:10'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
service_routing_protocols_model: multi-agent
snmp_server:
  location: HCA CAMPUS_A campus-a-leaf2b
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
  no_spanning_tree_vlan: 4093-4094
static_routes:
- vrf: default
  prefix: 0.0.0.0/0
  next_hop: 192.168.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4093
  description: MLAG_L3
  shutdown: false
  ip_address: 10.255.254.29/31
  mtu: 1500
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 10.255.255.29/31
  mtu: 1500
  no_autostate: true
- name: Vlan10
  description: MGMT
  shutdown: false
  ip_address_virtual: 10.10.10.1/24
  tenant: HCA
- name: Vlan20
  description: USER
  shutdown: false
  ip_address_virtual: 10.10.20.1/24
  tenant: HCA
- name: Vlan30
  description: VOICE
  shutdown: false
  ip_address_virtual: 10.10.30.1/24
  tenant: HCA
- name: Vlan40
  description: PACS
  shutdown: false
  ip_address_virtual: 10.10.40.1/24
  tenant: HCA
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4093
  name: MLAG_L3
  trunk_groups:
  - MLAG
  tenant: system
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
- id: 10
  name: MGMT
  tenant: HCA
- id: 20
  name: USER
  tenant: HCA
- id: 30
  name: VOICE
  tenant: HCA
- id: 40
  name: PACS
  tenant: HCA
vrfs:
- name: default
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: campus-a-leaf2b_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      virtual_router_encapsulation_mac_address: mlag-system-id
      vlans:
      - id: 10
        vni: 10010
      - id: 20
        vni: 10020
      - id: 30
        vni: 10030
      - id: 40
        vni: 10040
      vrfs:
      - name: default
        vni: 10
