aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet3
  description: MLAG_campus-a-leaf1a_Ethernet3
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: campus-a-leaf1a
  peer_interface: Ethernet3
  peer_type: mlag_peer
- name: Ethernet4
  description: MLAG_campus-a-leaf1a_Ethernet4
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: campus-a-leaf1a
  peer_interface: Ethernet4
  peer_type: mlag_peer
- name: Ethernet1
  description: P2P_campus-a-spine1_Ethernet6
  shutdown: false
  mtu: 1500
  ip_address: 172.31.254.53/31
  peer: campus-a-spine1
  peer_interface: Ethernet6
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_campus-a-spine2_Ethernet6
  shutdown: false
  mtu: 1500
  ip_address: 172.31.254.55/31
  peer: campus-a-spine2
  peer_interface: Ethernet6
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet5
  description: L2_campus-a-leaf2c_Ethernet2
  shutdown: false
  channel_group:
    id: 5
    mode: active
  peer: campus-a-leaf2c
  peer_interface: Ethernet2
  peer_type: l2leaf
- name: Ethernet6
  description: L2_campus-a-leaf2d_Ethernet2
  shutdown: false
  channel_group:
    id: 6
    mode: active
  peer: campus-a-leaf2d
  peer_interface: Ethernet2
  peer_type: l2leaf
- name: Management1
  lldp:
    transmit: false
    receive: false
hostname: campus-a-leaf1b
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$RWWNi/U4IjK9U3Nv$/bMitcVhMFiqvUIJtAAeTOTSyvqAHK.XpJi12NI0.YTJlzbl9FiCGi2EDfIWo14Evi/sj5i1Rxspmkbso0Tun1
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$6PorspAoWf2hUSNp$3CT1iPrvr7uhgCdAN2QBZuO7Aqu..EFjOK5SHUXSP44qJ91OQ/I.88B4iyDufM35wwqS1JhbmS3ejsDAxvOGL/
- name: robert
  privilege: 15
  role: network-admin
  no_password: true
  ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK7U+usFHr9Xhqph3HcmaWpi/Tjl0a3aof1AQRvSXuOw redmonds@redmonds
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.244.14/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.243.13/32
- name: Loopback100
  description: DIAG_VRF_Blue
  shutdown: false
  vrf: Blue
  ip_address: 192.168.200.14/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: default
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: default
  ip_address: 192.168.0.34/24
  type: oob
  gateway: 192.168.0.1
metadata:
  is_deployed: true
  platform: vEOS-LAB
  rack: Rack1A
  dc_name: CAMPUS_A
  fabric_name: HCA
mlag_configuration:
  domain_id: campus-a-leaf1
  local_interface: Vlan4094
  peer_address: 10.255.255.24
  peer_address_heartbeat:
    peer_ip: 192.168.0.33
    vrf: default
  dual_primary_detection_delay: 5
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_campus-a-leaf1a_Port-Channel3
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 2-4094
      groups:
      - MLAG
- name: Port-Channel5
  description: L2_campus-a-leaf2c_Port-Channel1
  shutdown: false
  mlag: 5
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 110-113,120-121,130-131
- name: Port-Channel6
  description: L2_campus-a-leaf2d_Port-Channel1
  shutdown: false
  mlag: 6
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 110-113,120-121,130-131
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.244.0/24 eq 32
  - sequence: 20
    action: permit 192.168.243.0/24 eq 32
- name: PL-MLAG-PEER-VRFS
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.254.24/31
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
    set:
    - origin incomplete
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-CONN-2-BGP-VRFS
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - ip address prefix-list PL-MLAG-PEER-VRFS
  - sequence: 20
    type: permit
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
router_bgp:
  as: '65102'
  router_id: 192.168.244.14
  maximum_paths:
    paths: 4
    ecmp: 4
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65102'
    description: campus-a-leaf1a
    next_hop_self: true
    password: vnEaG8gMeQf3d3cN6PktXQ==
    send_community: all
    maximum_routes: 12000
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    password: AQQvKeimxJu+uGQ/yYvv9w==
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    password: q+VNViP5i4rVjW1cxFv2wA==
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 10.255.254.24
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    peer: campus-a-leaf1a
    description: campus-a-leaf1a_Vlan4093
  - ip_address: 172.31.254.52
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: campus-a-spine1
    description: campus-a-spine1_Ethernet6
  - ip_address: 172.31.254.54
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: campus-a-spine2
    description: campus-a-spine2_Ethernet6
  - ip_address: 192.168.244.11
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65101'
    peer: campus-a-spine1
    description: campus-a-spine1_Loopback0
  - ip_address: 192.168.244.12
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65101'
    peer: campus-a-spine2
    description: campus-a-spine2_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlan_aware_bundles:
  - name: Blue
    rd: 192.168.244.14:10
    route_targets:
      both:
      - '10:10'
    redistribute_routes:
    - learned
    vlan: 110-113
  - name: Green
    rd: 192.168.244.14:12
    route_targets:
      both:
      - '12:12'
    redistribute_routes:
    - learned
    vlan: 130-131
  - name: Red
    rd: 192.168.244.14:11
    route_targets:
      both:
      - '11:11'
    redistribute_routes:
    - learned
    vlan: 120-121
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  vrfs:
  - name: Blue
    rd: 192.168.244.14:10
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '10:10'
      export:
      - address_family: evpn
        route_targets:
        - '10:10'
    router_id: 192.168.244.14
    neighbors:
    - ip_address: 10.255.254.24
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: campus-a-leaf1a_Vlan3009
    redistribute:
      connected:
        enabled: true
        route_map: RM-CONN-2-BGP-VRFS
  - name: Green
    rd: 192.168.244.14:12
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '12:12'
      export:
      - address_family: evpn
        route_targets:
        - '12:12'
    router_id: 192.168.244.14
    neighbors:
    - ip_address: 10.255.254.24
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: campus-a-leaf1a_Vlan3011
    redistribute:
      connected:
        enabled: true
        route_map: RM-CONN-2-BGP-VRFS
  - name: Red
    rd: 192.168.244.14:11
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '11:11'
      export:
      - address_family: evpn
        route_targets:
        - '11:11'
    router_id: 192.168.244.14
    neighbors:
    - ip_address: 10.255.254.24
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: campus-a-leaf1a_Vlan3010
    redistribute:
      connected:
        enabled: true
        route_map: RM-CONN-2-BGP-VRFS
service_routing_protocols_model: multi-agent
snmp_server:
  location: HCA CAMPUS_A Rack1A campus-a-leaf1b
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
  no_spanning_tree_vlan: 4093-4094
static_routes:
- vrf: default
  prefix: 0.0.0.0/0
  next_hop: 192.168.0.1
transceiver_qsfp_default_mode_4x10: true
virtual_source_nat_vrfs:
- name: Blue
  ip_address: 192.168.200.14
vlan_interfaces:
- name: Vlan4093
  description: MLAG_L3
  shutdown: false
  ip_address: 10.255.254.25/31
  mtu: 1500
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 10.255.255.25/31
  mtu: 1500
  no_autostate: true
- name: Vlan110
  description: Blue_110
  shutdown: false
  vrf: Blue
  ip_address_virtual: 192.168.210.1/24
  tenant: HCA
- name: Vlan111
  description: Blue_111
  shutdown: false
  vrf: Blue
  ip_address_virtual: 192.168.211.1/24
  tenant: HCA
- name: Vlan112
  description: Blue_112
  shutdown: false
  vrf: Blue
  ip_address_virtual: 192.168.212.1/24
  tenant: HCA
- name: Vlan113
  description: Blue_113
  shutdown: false
  vrf: Blue
  ip_address_virtual: 192.168.213.1/24
  tenant: HCA
- name: Vlan3009
  description: MLAG_L3_VRF_Blue
  shutdown: false
  vrf: Blue
  ip_address: 10.255.254.25/31
  mtu: 1500
  tenant: HCA
  type: underlay_peering
- name: Vlan130
  description: Green_130
  shutdown: false
  vrf: Green
  ip_address_virtual: 192.168.230.1/24
  tenant: HCA
- name: Vlan131
  description: Green_131
  shutdown: false
  vrf: Green
  ip_address_virtual: 192.168.231.1/24
  tenant: HCA
- name: Vlan3011
  description: MLAG_L3_VRF_Green
  shutdown: false
  vrf: Green
  ip_address: 10.255.254.25/31
  mtu: 1500
  tenant: HCA
  type: underlay_peering
- name: Vlan120
  description: Red_120
  shutdown: false
  vrf: Red
  ip_address_virtual: 192.168.220.1/24
  tenant: HCA
- name: Vlan121
  description: WEBZone_121
  shutdown: false
  vrf: Red
  ip_address_virtual: 192.168.221.1/24
  tenant: HCA
- name: Vlan3010
  description: MLAG_L3_VRF_Red
  shutdown: false
  vrf: Red
  ip_address: 10.255.254.25/31
  mtu: 1500
  tenant: HCA
  type: underlay_peering
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4093
  name: MLAG_L3
  trunk_groups:
  - MLAG
  tenant: system
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
- id: 110
  name: Blue_110
  tenant: HCA
- id: 111
  name: Blue_111
  tenant: HCA
- id: 112
  name: Blue_112
  tenant: HCA
- id: 113
  name: Blue_113
  tenant: HCA
- id: 3009
  name: MLAG_L3_VRF_Blue
  trunk_groups:
  - MLAG
  tenant: HCA
- id: 130
  name: Green_130
  tenant: HCA
- id: 131
  name: Green_131
  tenant: HCA
- id: 3011
  name: MLAG_L3_VRF_Green
  trunk_groups:
  - MLAG
  tenant: HCA
- id: 120
  name: Red_120
  tenant: HCA
- id: 121
  name: WEBZone_121
  tenant: HCA
- id: 3010
  name: MLAG_L3_VRF_Red
  trunk_groups:
  - MLAG
  tenant: HCA
vrfs:
- name: default
  ip_routing: false
- name: Blue
  ip_routing: true
  tenant: HCA
- name: Green
  ip_routing: true
  tenant: HCA
- name: Red
  ip_routing: true
  tenant: HCA
vxlan_interface:
  vxlan1:
    description: campus-a-leaf1b_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      virtual_router_encapsulation_mac_address: mlag-system-id
      vlans:
      - id: 110
        vni: 10110
      - id: 111
        vni: 50111
      - id: 112
        vni: 50112
      - id: 113
        vni: 10113
      - id: 130
        vni: 10130
      - id: 131
        vni: 10131
      - id: 120
        vni: 10120
      - id: 121
        vni: 10121
      vrfs:
      - name: Blue
        vni: 10
      - name: Green
        vni: 12
      - name: Red
        vni: 11
