aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_campus-b-leaf1a_Ethernet5
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: campus-b-leaf1a
  peer_interface: Ethernet5
  peer_type: l3leaf
- name: Ethernet2
  description: L2_campus-b-leaf1b_Ethernet5
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: campus-b-leaf1b
  peer_interface: Ethernet5
  peer_type: l3leaf
- name: Ethernet6
  description: SERVER_campus-b-leaf2-server1_Ethernet1
  shutdown: false
  channel_group:
    id: 6
    mode: active
  peer: campus-b-leaf2-server1
  peer_interface: Ethernet1
  peer_type: server
  port_profile: TENANT_A_Vl110
- name: Management1
  lldp:
    transmit: false
    receive: false
hostname: campus-b-leaf2c
ip_igmp_snooping:
  globally_enabled: true
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$RWWNi/U4IjK9U3Nv$/bMitcVhMFiqvUIJtAAeTOTSyvqAHK.XpJi12NI0.YTJlzbl9FiCGi2EDfIWo14Evi/sj5i1Rxspmkbso0Tun1
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$6PorspAoWf2hUSNp$3CT1iPrvr7uhgCdAN2QBZuO7Aqu..EFjOK5SHUXSP44qJ91OQ/I.88B4iyDufM35wwqS1JhbmS3ejsDAxvOGL/
- name: robert
  privilege: 15
  role: network-admin
  no_password: true
  ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK7U+usFHr9Xhqph3HcmaWpi/Tjl0a3aof1AQRvSXuOw redmonds@redmonds
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.47/24
  type: oob
  gateway: 192.168.0.1
metadata:
  is_deployed: true
  platform: vEOS-LAB
  dc_name: CAMPUS_B
  fabric_name: HCA
port_channel_interfaces:
- name: Port-Channel1
  description: L2_campus-b-leaf1_Port-Channel5
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 110-113,120-121,130-131
- name: Port-Channel6
  description: SERVER_campus-b-leaf2-server1
  shutdown: false
  switchport:
    enabled: true
    mode: access
    access_vlan: 110
service_routing_protocols_model: multi-agent
snmp_server:
  location: HCA CAMPUS_B campus-b-leaf2c
static_routes:
- vrf: MGMT
  prefix: 0.0.0.0/0
  next_hop: 192.168.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 110
  name: Blue_110
  tenant: HCA
- id: 111
  name: Blue_111
  tenant: HCA
- id: 112
  name: Blue_112
  tenant: HCA
- id: 113
  name: Blue_113
  tenant: HCA
- id: 130
  name: Green_130
  tenant: HCA
- id: 131
  name: Green_131
  tenant: HCA
- id: 120
  name: Red_120
  tenant: HCA
- id: 121
  name: WEBZone_121
  tenant: HCA
vrfs:
- name: MGMT
  ip_routing: false
