anta.tests.connectivity:
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: campus-a-leaf2a
      neighbor_port: Ethernet3
      port: Ethernet3
    result_overwrite:
      custom_field: 'Local: Ethernet3 - Remote: campus-a-leaf2a Ethernet3'
- VerifyLLDPNeighbors:
    neighbors:
    - neighbor_device: campus-a-leaf2a
      neighbor_port: Ethernet4
      port: Ethernet4
    result_overwrite:
      custom_field: 'Local: Ethernet4 - Remote: campus-a-leaf2a Ethernet4'
- VerifyReachability:
    hosts:
    - destination: 192.168.244.11
      repeat: 1
      source: 192.168.244.16
      vrf: default
    result_overwrite:
      custom_field: 'Source: Loopback0 (IP: 192.168.244.16) - Destination: campus-a-spine1
        Loopback0 (IP: 192.168.244.11)'
- VerifyReachability:
    hosts:
    - destination: 192.168.244.12
      repeat: 1
      source: 192.168.244.16
      vrf: default
    result_overwrite:
      custom_field: 'Source: Loopback0 (IP: 192.168.244.16) - Destination: campus-a-spine2
        Loopback0 (IP: 192.168.244.12)'
- VerifyReachability:
    hosts:
    - destination: 192.168.244.13
      repeat: 1
      source: 192.168.244.16
      vrf: default
    result_overwrite:
      custom_field: 'Source: Loopback0 (IP: 192.168.244.16) - Destination: campus-a-leaf1a
        Loopback0 (IP: 192.168.244.13)'
- VerifyReachability:
    hosts:
    - destination: 192.168.244.14
      repeat: 1
      source: 192.168.244.16
      vrf: default
    result_overwrite:
      custom_field: 'Source: Loopback0 (IP: 192.168.244.16) - Destination: campus-a-leaf1b
        Loopback0 (IP: 192.168.244.14)'
- VerifyReachability:
    hosts:
    - destination: 192.168.244.15
      repeat: 1
      source: 192.168.244.16
      vrf: default
    result_overwrite:
      custom_field: 'Source: Loopback0 (IP: 192.168.244.16) - Destination: campus-a-leaf2a
        Loopback0 (IP: 192.168.244.15)'
- VerifyReachability:
    hosts:
    - destination: 192.168.244.16
      repeat: 1
      source: 192.168.244.16
      vrf: default
    result_overwrite:
      custom_field: 'Source: Loopback0 (IP: 192.168.244.16) - Destination: campus-a-leaf2b
        Loopback0 (IP: 192.168.244.16)'
anta.tests.interfaces:
- VerifyInterfacesStatus:
    interfaces:
    - name: Ethernet3
      status: up
    result_overwrite:
      custom_field: Interface Ethernet3 - MLAG_campus-a-leaf2a_Ethernet3 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Ethernet4
      status: up
    result_overwrite:
      custom_field: Interface Ethernet4 - MLAG_campus-a-leaf2a_Ethernet4 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Management1
      status: up
    result_overwrite:
      custom_field: Interface Management1 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Port-Channel3
      status: up
    result_overwrite:
      custom_field: Interface Port-Channel3 - MLAG_campus-a-leaf2a_Port-Channel3 =
        'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan4093
      status: up
    result_overwrite:
      custom_field: Interface Vlan4093 - MLAG_L3 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan4094
      status: up
    result_overwrite:
      custom_field: Interface Vlan4094 - MLAG = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan110
      status: up
    result_overwrite:
      custom_field: Interface Vlan110 - Blue_110 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan111
      status: up
    result_overwrite:
      custom_field: Interface Vlan111 - Blue_111 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan112
      status: up
    result_overwrite:
      custom_field: Interface Vlan112 - Blue_112 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan113
      status: up
    result_overwrite:
      custom_field: Interface Vlan113 - Blue_113 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan3009
      status: up
    result_overwrite:
      custom_field: Interface Vlan3009 - MLAG_L3_VRF_Blue = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan130
      status: up
    result_overwrite:
      custom_field: Interface Vlan130 - Green_130 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan131
      status: up
    result_overwrite:
      custom_field: Interface Vlan131 - Green_131 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan3011
      status: up
    result_overwrite:
      custom_field: Interface Vlan3011 - MLAG_L3_VRF_Green = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan120
      status: up
    result_overwrite:
      custom_field: Interface Vlan120 - Red_120 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan121
      status: up
    result_overwrite:
      custom_field: Interface Vlan121 - WEBZone_121 = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vlan3010
      status: up
    result_overwrite:
      custom_field: Interface Vlan3010 - MLAG_L3_VRF_Red = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Loopback0
      status: up
    result_overwrite:
      custom_field: Interface Loopback0 - ROUTER_ID = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Loopback1
      status: up
    result_overwrite:
      custom_field: Interface Loopback1 - VXLAN_TUNNEL_SOURCE = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Loopback100
      status: up
    result_overwrite:
      custom_field: Interface Loopback100 - DIAG_VRF_Blue = 'up'
- VerifyInterfacesStatus:
    interfaces:
    - name: Vxlan1
      status: up
    result_overwrite:
      custom_field: Interface Vxlan1 = 'up'
anta.tests.mlag:
- VerifyMlagStatus: null
anta.tests.routing.bgp:
- VerifyBGPSpecificPeers:
    address_families:
    - afi: ipv4
      peers:
      - 10.255.254.28
      safi: unicast
    result_overwrite:
      custom_field: 'BGP IPv4 Unicast Peer: campus-a-leaf2a (IP: 10.255.254.28)'
anta.tests.routing.generic:
- VerifyRoutingProtocolModel:
    model: multi-agent
    result_overwrite:
      custom_field: 'Routing protocol model: multi-agent'
- VerifyRoutingTableEntry:
    result_overwrite:
      custom_field: 'Route: 192.168.244.11 - Peer: campus-a-spine1'
    routes:
    - 192.168.244.11
- VerifyRoutingTableEntry:
    result_overwrite:
      custom_field: 'Route: 192.168.244.12 - Peer: campus-a-spine2'
    routes:
    - 192.168.244.12
- VerifyRoutingTableEntry:
    result_overwrite:
      custom_field: 'Route: 192.168.244.13 - Peer: campus-a-leaf1a'
    routes:
    - 192.168.244.13
- VerifyRoutingTableEntry:
    result_overwrite:
      custom_field: 'Route: 192.168.244.14 - Peer: campus-a-leaf1b'
    routes:
    - 192.168.244.14
- VerifyRoutingTableEntry:
    result_overwrite:
      custom_field: 'Route: 192.168.244.15 - Peer: campus-a-leaf2a'
    routes:
    - 192.168.244.15
- VerifyRoutingTableEntry:
    result_overwrite:
      custom_field: 'Route: 192.168.244.16 - Peer: campus-a-leaf2b'
    routes:
    - 192.168.244.16
- VerifyRoutingTableEntry:
    result_overwrite:
      custom_field: 'Route: 192.168.243.13 - Peer: campus-a-leaf1a'
    routes:
    - 192.168.243.13
- VerifyRoutingTableEntry:
    result_overwrite:
      custom_field: 'Route: 192.168.243.15 - Peer: campus-a-leaf2a'
    routes:
    - 192.168.243.15
anta.tests.system:
- VerifyNTP: null
- VerifyReloadCause: null
